server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock

    pipeline_stages:
      # 1️⃣ Parse JSON
      - json:
          expressions:
            levelname: levelname
            message: message
            logger: name

      # 2️⃣ Promote to labels (THIS WAS MISSING)
      - labels:
          levelname:
          logger: